Using advice-around instead of hook trigger for mode enable.
ncaq/auto-sudoedit pull request #6
Opened 2019-07-28 03:53 UTC by c0001

The original funcition `auto-sudoedit-sudoedit-and-kill' using buffer
redirect method to replace the origin dired displayed buffer with the
tramped one, and indeed that this procedure working for the hook both
for `dired-mode-hook' or `find-file-hook' caused by the original `auto
-sudoedit-mode' trigger. But for thus, the `kill-this-buffer' way will
corrupted the origin buffer argument for the next hook rounder which
will destroyed the whole dired or find-file initializing procedure.

For avoiding this problem, this commit using the around-advices
re-wrappering the `dired' and `find-file' which just transfer the
tramp-transfered path for the rest process powered by the original
package builtin function `auto-sudoedit-tramp-path'.

2019-08-01 05:21 UTC, ncaq requested changes

2019-08-01 05:21 UTC, ncaq commented on auto-sudoedit.el
> +(defun auto-sudoedit (_old_func &rest _args)
The `args` arguments is used.
However this naming starting underscore.
underscore show unused variable.
I think to should naming normal.

2019-08-01 05:21 UTC, ncaq commented on auto-sudoedit.el
> +      (apply _old_func _args))))
and, these argumest is used.

2019-08-01 05:21 UTC, ncaq commented on auto-sudoedit.el
> +(defun auto-sudoedit (_old_func &rest _args)
`_old_func` show old function.
I think that is for example `original-function` or `orig-func` is more better.

2019-08-08 13:38 UTC, c0001 commented
Sorry for a week delayed thus.

Thanks for your reviews, the naming convention problems has been fixed
yet. I've tested and the monitoring the trails for a week as seeking
the decision reliable done. :)

2019-08-09 07:35 UTC, ncaq approved these changes

2019-08-09 07:35 UTC, merged